"""
药食同源知识图谱 —— 英文→中文医学术语翻译词典
涵盖 400+ 医学词汇，覆盖神经系统、肿瘤、心血管、消化、遗传等各领域。
"""

# 英文医学术语 → 中文翻译
EN_TO_CN_MEDICAL = {
    # === 疾病基础 ===
    "disease": "病", "diseases": "病", "disorder": "障碍", "disorders": "障碍",
    "syndrome": "综合征", "syndromes": "综合征",
    "deficiency": "缺乏症", "defect": "缺陷", "defects": "缺陷",
    "abnormality": "异常", "abnormalities": "异常",
    "anomaly": "畸形", "anomalies": "畸形",
    "malformation": "畸形", "malformations": "畸形",
    "dysfunction": "功能障碍", "insufficiency": "功能不全",
    "failure": "衰竭", "necrosis": "坏死", "fibrosis": "纤维化",
    "sclerosis": "硬化", "atrophy": "萎缩", "hypertrophy": "肥大",
    "hyperplasia": "增生", "metaplasia": "化生", "dysplasia": "发育异常",
    "hypoplasia": "发育不全", "aplasia": "不发育", "agenesis": "发育不全",
    "dysgenesis": "发育不良", "degeneration": "变性",
    "calcification": "钙化", "ossification": "骨化", "steatosis": "脂肪变",
    "cirrhosis": "肝硬化", "stenosis": "狭窄", "obstruction": "梗阻",
    "occlusion": "闭塞", "hemorrhage": "出血", "thrombosis": "血栓形成",
    "embolism": "栓塞", "infarction": "梗死", "ischemia": "缺血", "edema": "水肿",
    "infection": "感染", "infections": "感染",
    "inflammation": "炎症", "inflammatory": "炎性",

    # === 肿瘤 ===
    "cancer": "癌", "carcinoma": "癌", "tumor": "瘤", "tumors": "瘤",
    "neoplasm": "肿瘤", "neoplasms": "肿瘤",
    "leukemia": "白血病", "lymphoma": "淋巴瘤", "sarcoma": "肉瘤",
    "melanoma": "黑色素瘤", "adenoma": "腺瘤", "adenocarcinoma": "腺癌",
    "meningioma": "脑膜瘤", "astrocytoma": "星形细胞瘤",
    "glioblastoma": "胶质母细胞瘤", "glioma": "胶质瘤",
    "myeloma": "骨髓瘤", "neuroblastoma": "神经母细胞瘤",
    "retinoblastoma": "视网膜母细胞瘤", "nephroblastoma": "肾母细胞瘤",
    "hepatoblastoma": "肝母细胞瘤", "pheochromocytoma": "嗜铬细胞瘤",
    "teratoma": "畸胎瘤", "hamartoma": "错构瘤", "papilloma": "乳头状瘤",
    "malignant": "恶性", "benign": "良性",
    "metastatic": "转移性", "invasive": "浸润性",
    "squamous": "鳞状", "basal": "基底细胞",
    "myeloid": "髓系", "lymphoid": "淋巴系",

    # === 遗传/发育 ===
    "congenital": "先天性", "congenita": "先天性",
    "hereditary": "遗传性", "familial": "家族性",
    "sporadic": "散发性", "idiopathic": "特发性",
    "autosomal": "常染色体", "recessive": "隐性", "dominant": "显性",
    "x-linked": "X连锁", "y-linked": "Y连锁",
    "chromosome": "染色体", "chromosomal": "染色体",
    "genetic": "遗传", "mitochondrial": "线粒体",
    "mutation": "突变", "deletion": "缺失", "duplication": "重复",
    "translocation": "易位", "inversion": "倒位",
    "microdeletion": "微缺失", "microduplication": "微重复",
    "complementation": "互补", "locus": "基因座",
    "susceptibility": "易感性", "resistance": "抵抗",
    "developmental": "发育性", "development": "发育",
    "growth": "生长", "delay": "迟缓", "retardation": "发育迟缓",
    "intellectual": "智力障碍", "mental": "精神智力",
    "cognitive": "认知", "memory": "记忆",
    "neurodevelopmental": "神经发育",

    # === 神经/精神 ===
    "dementia": "痴呆", "alzheimer": "阿尔茨海默", "parkinson": "帕金森",
    "schizophrenia": "精神分裂症", "depression": "抑郁症", "depressive": "抑郁",
    "anxiety": "焦虑", "autism": "自闭症", "bipolar": "双相",
    "epilepsy": "癫痫", "epileptic": "癫痫性", "seizures": "癫痫发作",
    "hallucinations": "幻觉", "psychosis": "精神病",
    "ataxia": "共济失调", "dystonia": "肌张力障碍",
    "tremor": "震颤", "myoclonus": "肌阵挛", "myoclonic": "肌阵挛性",
    "chorea": "舞蹈症", "spastic": "痉挛性", "spasticity": "痉挛",
    "paralysis": "瘫痪", "palsy": "麻痹", "paraplegia": "截瘫",
    "hemiplegia": "偏瘫", "quadriplegia": "四肢瘫",
    "reflex": "反射", "motor": "运动", "sensory": "感觉",
    "neural": "神经", "neurologic": "神经", "neuralgia": "神经痛",
    "neuropathy": "神经病变", "polyneuropathy": "多发性神经病",
    "encephalopathy": "脑病", "myelopathy": "脊髓病",
    "amyotrophic": "肌萎缩性", "lateral": "侧索",
    "spinocerebellar": "脊髓小脑", "cerebellar": "小脑",
    "aphasia": "失语症", "apraxia": "失用症", "agnosia": "失认症",
    "narcolepsy": "发作性睡病", "insomnia": "失眠", "sleep": "睡眠",
    "migraine": "偏头痛", "headache": "头痛",
    "vertigo": "眩晕", "tinnitus": "耳鸣",
    "delirium": "谵妄", "amnestic": "遗忘型",
    "paranoid": "偏执型", "impairment": "损伤",
    "cognitive": "认知", "impaired": "受损",
    "presenile": "早老性", "senile": "老年性",
    "frontotemporal": "额颞叶", "subcortical": "皮质下",
    "arteriosclerotic": "动脉硬化性", "vascular": "血管性",
    "semantic": "语义性",

    # === 肌肉/骨骼 ===
    "muscle": "肌肉", "muscular": "肌肉",
    "myopathy": "肌病", "myasthenic": "肌无力",
    "dystrophy": "营养不良", "myotonic": "肌强直性",
    "myositis": "肌炎", "rhabdomyolysis": "横纹肌溶解",
    "bone": "骨", "skeletal": "骨骼", "joint": "关节",
    "articular": "关节", "arthritis": "关节炎", "arthropathy": "关节病",
    "osteoporosis": "骨质疏松", "osteopetrosis": "骨硬化症",
    "osteogenesis": "成骨", "imperfecta": "不全",
    "chondrodysplasia": "软骨发育不良",
    "scoliosis": "脊柱侧弯", "kyphosis": "脊柱后凸",
    "spondylitis": "脊柱炎",
    "brachydactyly": "短指趾畸形", "syndactyly": "并指趾畸形",
    "polydactyly": "多指趾畸形",
    "cleft": "裂", "lip": "唇", "palate": "腭",
    "gait": "步态", "stature": "身材",

    # === 心血管 ===
    "heart": "心脏", "cardiac": "心脏", "cardio": "心脏",
    "cardiomyopathy": "心肌病", "myocarditis": "心肌炎",
    "myocardial": "心肌", "coronary": "冠状动脉",
    "atrial": "心房", "ventricular": "心室",
    "fibrillation": "颤动", "arrhythmia": "心律失常",
    "tachycardia": "心动过速", "bradycardia": "心动过缓",
    "hypertension": "高血压", "hypotension": "低血压",
    "aneurysm": "动脉瘤", "dissection": "夹层",
    "artery": "动脉", "arterial": "动脉", "aortic": "主动脉",
    "carotid": "颈动脉", "venous": "静脉",
    "dilated": "扩张性", "hypertrophic": "肥厚性",
    "pulmonary": "肺", "respiratory": "呼吸",

    # === 五官 ===
    "eye": "眼", "ocular": "眼", "optic": "视神经",
    "retinal": "视网膜", "retinitis": "视网膜炎",
    "pigmentosa": "色素性", "macular": "黄斑",
    "corneal": "角膜", "cataract": "白内障", "glaucoma": "青光眼",
    "coloboma": "缺损", "microphthalmia": "小眼畸形",
    "deafness": "耳聋", "hearing": "听力", "blindness": "失明",

    # === 皮肤 ===
    "skin": "皮肤", "cutaneous": "皮肤", "dermatitis": "皮炎",
    "eczema": "湿疹", "psoriasis": "银屑病", "urticaria": "荨麻疹",
    "nevus": "痣", "melanocytic": "黑素细胞",
    "bullosa": "大疱性", "epidermolysis": "表皮松解",
    "ichthyosis": "鱼鳞病", "keratoderma": "角皮病",
    "palmoplantar": "掌跖", "ectodermal": "外胚层",
    "hair": "毛发", "alopecia": "脱发", "hirsutism": "多毛症",
    "hypotrichosis": "毛发稀少", "cutis": "皮肤",
    "albinism": "白化病", "vitiligo": "白癜风",
    "acne": "痤疮", "pruritus": "瘙痒", "rash": "皮疹",

    # === 消化 ===
    "stomach": "胃", "gastric": "胃", "intestinal": "肠",
    "colon": "结肠", "colorectal": "结直肠", "colitis": "结肠炎",
    "esophagus": "食管", "esophageal": "食管",
    "esophagitis": "食管炎", "gastritis": "胃炎",
    "pancreatic": "胰腺", "pancreatitis": "胰腺炎",
    "liver": "肝", "hepatic": "肝", "hepatitis": "肝炎",
    "peptic": "消化性", "ulcer": "溃疡",

    # === 泌尿/生殖 ===
    "kidney": "肾", "renal": "肾", "nephritis": "肾炎",
    "nephrotic": "肾病", "nephropathy": "肾病",
    "tubular": "肾小管", "glomerular": "肾小球",
    "bladder": "膀胱", "urinary": "泌尿",
    "prostate": "前列腺", "prostatic": "前列腺",
    "ovary": "卵巢", "ovarian": "卵巢",
    "testicular": "睾丸", "testis": "睾丸",
    "uterine": "子宫", "uterus": "子宫", "cervical": "宫颈",
    "endometrial": "子宫内膜", "endometriosis": "子宫内膜异位",
    "breast": "乳腺", "mammary": "乳腺",
    "pregnancy": "妊娠", "postpartum": "产后",
    "menstrual": "月经", "menopause": "更年期",
    "infertility": "不孕",
    "polycystic": "多囊", "fibroids": "肌瘤",
    "hypogonadism": "性腺功能减退", "hypogonadotropic": "低促性腺激素性",

    # === 内分泌/代谢 ===
    "diabetes": "糖尿病", "mellitus": "糖尿病", "diabetic": "糖尿病",
    "thyroid": "甲状腺", "hyperthyroidism": "甲亢",
    "hypothyroidism": "甲减", "goiter": "甲状腺肿",
    "adrenal": "肾上腺", "pituitary": "垂体",
    "hormone": "激素", "hormonal": "激素",
    "metabolic": "代谢", "metabolism": "代谢",
    "obesity": "肥胖", "overweight": "超重",
    "lipid": "脂质", "cholesterol": "胆固醇",
    "hyperlipidemia": "高脂血症", "hypercholesterolemia": "高胆固醇血症",
    "gout": "痛风", "uric": "尿酸",
    "glycogen": "糖原", "storage": "贮积",
    "acidosis": "酸中毒", "aciduria": "酸尿症",
    "dehydrogenase": "脱氢酶", "oxidase": "氧化酶",
    "reductase": "还原酶", "transferase": "转移酶",
    "phosphorylation": "磷酸化", "oxidative": "氧化",
    "glycosylation": "糖基化",
    "protein": "蛋白", "receptor": "受体",
    "factor": "因子", "coagulation": "凝血",
    "amyloid": "淀粉样", "amyloidosis": "淀粉样变性",

    # === 血液/免疫 ===
    "blood": "血液", "hematologic": "血液",
    "anemia": "贫血", "anemias": "贫血",
    "hemolytic": "溶血性", "aplastic": "再生障碍性",
    "sickle": "镰状", "thalassemia": "地中海贫血",
    "hemophilia": "血友病", "thrombocytopenia": "血小板减少",
    "purpura": "紫癜", "pancytopenia": "全血细胞减少",
    "immune": "免疫", "immunodeficiency": "免疫缺陷",
    "autoimmune": "自身免疫", "allergic": "过敏性",
    "hypersensitivity": "超敏反应", "anaphylaxis": "过敏性休克",
    "aids": "艾滋病", "hiv": "HIV",
    "t-cell": "T细胞", "b-cell": "B细胞",

    # === 感染 ===
    "viral": "病毒性", "bacterial": "细菌性",
    "fungal": "真菌性", "parasitic": "寄生虫性",
    "tuberculosis": "结核", "malaria": "疟疾", "sepsis": "败血症",
    "pneumonia": "肺炎", "bronchitis": "支气管炎",
    "sinusitis": "鼻窦炎", "meningitis": "脑膜炎",
    "encephalitis": "脑炎", "endocarditis": "心内膜炎",
    "peritonitis": "腹膜炎", "osteomyelitis": "骨髓炎",
    "herpes": "疱疹", "zoster": "带状疱疹",

    # === 分型/程度 ===
    "type": "型", "types": "型", "group": "组",
    "variant": "变异型", "subtype": "亚型",
    "acute": "急性", "chronic": "慢性", "subacute": "亚急性",
    "primary": "原发性", "secondary": "继发性",
    "early": "早期", "late": "晚期", "advanced": "晚期",
    "onset": "发病", "early-onset": "早发性",
    "mild": "轻度", "moderate": "中度", "severe": "重度",
    "critical": "危重", "lethal": "致死性",
    "localized": "局限性", "generalized": "全身性",
    "systemic": "系统性", "disseminated": "播散性",
    "unilateral": "单侧", "bilateral": "双侧",
    "multiple": "多发性", "isolated": "孤立性",
    "combined": "联合性", "mixed": "混合性", "complex": "复合体",
    "transient": "一过性", "persistent": "持续性", "permanent": "永久性",
    "progressive": "进行性", "regressive": "退行性", "stable": "稳定性",
    "paroxysmal": "阵发性", "periodic": "周期性",
    "recurrent": "复发性", "relapsing": "复发性",
    "refractory": "难治性", "resistant": "耐药性",
    "undifferentiated": "未分化", "differentiated": "分化",
    "anaplastic": "间变性", "pleomorphic": "多形性",
    "atypical": "非典型", "typical": "典型",
    "classic": "经典型", "classical": "经典型",

    # === 原因 ===
    "toxic": "中毒性", "traumatic": "创伤性",
    "iatrogenic": "医源性", "drug": "药物性",
    "alcohol": "酒精性", "radiation": "放射性",
    "chemical": "化学性", "nutritional": "营养性",
    "experimental": "实验性", "induced": "诱导性",
    "abuse": "滥用", "poisoning": "中毒",
    "addiction": "成瘾", "dependence": "依赖",

    # === 年龄/性别 ===
    "juvenile": "青少年型", "infantile": "婴儿型",
    "neonatal": "新生儿", "childhood": "儿童期",
    "adolescent": "青少年", "adult": "成人型",
    "fetal": "胎儿", "premature": "早产",

    # === 解剖 ===
    "brain": "脑", "cerebral": "脑", "cortical": "皮质",
    "spinal": "脊髓", "cord": "脊髓", "nerve": "神经",
    "nervous": "神经", "system": "系统",
    "central": "中枢", "peripheral": "周围",
    "anterior": "前", "posterior": "后",
    "distal": "远端", "proximal": "近端",
    "facial": "面部", "oral": "口腔",
    "nasal": "鼻", "pharyngeal": "咽",
    "laryngeal": "喉", "tracheal": "气管",
    "lung": "肺", "diaphragm": "膈肌",
    "abdominal": "腹部", "pelvic": "骨盆",
    "inguinal": "腹股沟", "body": "身体",

    # === 特殊疾病名 ===
    "charcot-marie-tooth": "Charcot-Marie-Tooth",
    "ehlers-danlos": "Ehlers-Danlos",
    "fanconi": "Fanconi", "marfan": "Marfan",
    "wilson": "Wilson", "menkes": "Menkes",
    "rett": "Rett", "noonan": "Noonan", "turner": "Turner",
    "klinefelter": "Klinefelter", "down": "Down",
    "waardenburg": "Waardenburg", "alport": "Alport",
    "bartter": "Bartter", "gitelman": "Gitelman", "liddle": "Liddle",
    "usher": "Usher", "fragile": "脆性",
    "limb": "肢体", "acquired": "获得性",
    "finding": "表现", "trait": "性状",
    "short": "短", "long": "长", "like": "样",
    "nuclear": "核", "dna": "DNA",
}
